name: tlum
summary: (WIP) Open source code cross-platform language learning application
version: 0.0.1+1
description: |
  [DEMO] [Work in Progress: https://github.com/lyskouski/app-language] Open source code cross-platform language 
  learning application leverages the power of natural language processing to pinpoint pronunciation gaps, computer 
  vision to enhance articulation, and machine learning to boost vocabulary proficiency.
base: core22
confinement: strict

parts:
  tlum:
    plugin: python
    source: .
    stage-packages:
      - ffmpeg
      - libpulse0
      - libpulse-mainloop-glib0
      - libasound2
      - libasound2-plugins
      - libportaudio2
      - libsdl2-2.0-0
      - libsdl2-mixer-2.0-0
      - libsndfile1
      - xclip
      - xsel
    override-build: |
      python3 -m pip install --upgrade pip
      python3 -m pip install --prefix=$SNAPCRAFT_PART_INSTALL -r requirements.txt
      snapcraftctl build
      cp -r src $SNAPCRAFT_PART_INSTALL/
      cp -r assets $SNAPCRAFT_PART_INSTALL/

apps:
  tlum:
    command: bin/python3 $SNAP/src/main.py
    environment:
      KIVY_AUDIO: sdl2,ffpyplayer
      XDG_RUNTIME_DIR: /tmp
      SDL_AUDIODRIVER: pulse
      PULSE_SERVER: unix:/run/user/1000/pulse/native
      LD_LIBRARY_PATH: $SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
      KIVY_WINDOW: sdl2
      KIVY_GL_BACKEND: gl
    plugs:
      - home
      - desktop
      - network
      - opengl
      - x11
      - audio-playback
      - audio-record
      - pulseaudio
    extensions:
      - gnome
