name: tlum
summary: (WIP) Open source code cross-platform language learning application
version: 0.0.1+1
description: |
  [DEMO] [Work in Progress: https://github.com/lyskouski/app-language] Open source code cross-platform language 
  learning application leverages the power of natural language processing to pinpoint pronunciation gaps, computer 
  vision to enhance articulation, and machine learning to boost vocabulary proficiency.
base: core22
confinement: strict

parts:
  tlum:
    plugin: python
    source: .
    stage-packages:
      - ffmpeg
    override-build: |
      snapcraftctl build
      cp -r src $SNAPCRAFT_PART_INSTALL/
      cp -r assets $SNAPCRAFT_PART_INSTALL/

apps:
  tlum:
    command: bin/python3 $SNAP/src/main.py
    plugs:
      - home
      - desktop
      - network
      - opengl
      - x11
      - audio-playback
    extensions:
      - gnome
