#!/usr/bin/env python3
"""Forces manual code signing on the Xcode project generated by `buildozer ios`.

buildozer's ios target always passes `-allowProvisioningUpdates` to xcodebuild without any
account/API-key auth, which fails in CI ("No Accounts", "No profiles found") because the
kivy-ios template project defaults to Automatic signing. This switches the target to Manual
signing using the certificate/profile imported into the CI keychain, so no Apple account
negotiation is needed at build time.

Usage: configure_code_signing.py <project.pbxproj path> <target name> <code sign identity>
                                  <development team id> <provisioning profile UUID>
                                  <provisioning profile name>
"""
import sys

from pbxproj import XcodeProject


def main():
    pbxproj_path, target_name, identity, team, profile_uuid, profile_name = sys.argv[1:7]
    project = XcodeProject.load(pbxproj_path)
    project.add_code_sign(identity, team, profile_uuid, profile_name, target_name=target_name)
    project.save()
    print(f"Configured manual code signing for target '{target_name}' in {pbxproj_path}")


if __name__ == "__main__":
    main()
