#!/bin/sh
# Patches the Info.plist generated by `buildozer ios` with keys buildozer itself
# does not manage (microphone usage, supported orientations, launch behaviour).
# Must run after the Xcode project has been created/updated by buildozer and
# before the final `buildozer ios release` pass that produces the IPA, since
# buildozer reloads/re-saves this file on every invocation but only overwrites
# the keys it knows about.
#
# Usage: ios/patch_info_plist.sh /path/to/<app>-Info.plist
set -e

PLIST="$1"
if [ -z "$PLIST" ] || [ ! -f "$PLIST" ]; then
  echo "patch_info_plist.sh: Info.plist not found at '$PLIST'" >&2
  exit 1
fi

set_string() {
  key="$1"; value="$2"
  /usr/libexec/PlistBuddy -c "Delete :$key" "$PLIST" 2>/dev/null || true
  /usr/libexec/PlistBuddy -c "Add :$key string $value" "$PLIST"
}

set_bool() {
  key="$1"; value="$2"
  /usr/libexec/PlistBuddy -c "Delete :$key" "$PLIST" 2>/dev/null || true
  /usr/libexec/PlistBuddy -c "Add :$key bool $value" "$PLIST"
}

# Required because src/controller/recorder_controller_ios.py uses AVAudioSession/AVAudioRecorder.
set_string NSMicrophoneUsageDescription "Tlum uses the microphone to record your pronunciation for practice."

# Matches buildozer.spec `orientation = landscape`.
/usr/libexec/PlistBuddy -c "Delete :UISupportedInterfaceOrientations" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations array" "$PLIST"
/usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations:0 string UIInterfaceOrientationLandscapeLeft" "$PLIST"
/usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations:1 string UIInterfaceOrientationLandscapeRight" "$PLIST"

/usr/libexec/PlistBuddy -c "Delete :UISupportedInterfaceOrientations~ipad" "$PLIST" 2>/dev/null || true
/usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations~ipad array" "$PLIST"
/usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations~ipad:0 string UIInterfaceOrientationLandscapeLeft" "$PLIST"
/usr/libexec/PlistBuddy -c "Add :UISupportedInterfaceOrientations~ipad:1 string UIInterfaceOrientationLandscapeRight" "$PLIST"

# Matches buildozer.spec `fullscreen = 1`.
set_bool UIRequiresFullScreen true
set_bool UIStatusBarHidden true

echo "Patched $PLIST"
/usr/libexec/PlistBuddy -c "Print" "$PLIST"
