labels = {
    "en": {
        "status_saving": "Saving...",
        "status_select_sentence": "Select a sentence",
        "status_recording": "Recording...",
        "status_recording_stopped": "Recording stopped",
        "game_phonetics": "Phonetics",
        "game_harmonica": "Harmonica",
        "game_articulation": "Articulation",
        "error_not_found": "Error: No recorded file found",
        "button_update": "Update",
        "button_stop_recording": "Stop Recording",
        "button_shuffle": "Shuffle",
        "button_select": "Select",
        "button_save": "Save",
        "button_record": "Record",
        "button_processing": "Processing",
        "button_play": "Play",
        "button_listen": "Listen",
        "button_clear": "Clear",
        "button_choose": "Choose",
        "button_add": "Add",
        "_": "Fatal Error"
    },
    "ru": {
        "status_saving": "Сохранение...",
        "status_select_sentence": "Выберите предложение",
        "status_recording": "Запись...",
        "status_recording_stopped": "Запись остановлена",
        "game_phonetics": "Фонетика",
        "game_harmonica": "Гармошка",
        "game_articulation": "Артикуляция",
        "error_not_found": "Ошибка: Записанный файл не найден",
        "button_update": "Обновить",
        "button_stop_recording": "Остановить запись",
        "button_shuffle": "Перемешать",
        "button_select": "Выбрать",
        "button_save": "Сохранить",
        "button_record": "Записать",
        "button_processing": "Обработка...",
        "button_play": "Играть",
        "button_listen": "Слушать",
        "button_clear": "Очистить",
        "button_choose": "Выбрать",
        "button_add": "Добавить",
        "_": "Фатальная ошибка"
    }
}
