labels_be = {
    "status_saving": "Захоўваецца...",
    "status_select_sentence": "Выберыце сказ",
    "status_recording": "Запіс...",
    "status_recording_stopped": "Запіс спынены",
    "status_loading": "Загрузка...",
    "field_text": "Загаловак",
    "field_text__hint": "Увядзіце тэкст",
    "field_source": "Крыніца",
    "field_source__hint": "Увядзіце крыніцу",
    "field_logo": "Лагатып",
    "field_logo__hint": "Увядзіце лагатып",
    "field_store_path": "Шлях да сховішча дадзеных",
    "field_store_path__hint": "Увядзіце шлях да сховішча дадзеных",
    "field_route_path": "Шлях маршруту",
    "field_route_path__hint": "Увядзіце шлях маршруту",
    "field_locale": "Лакалізацыя",
    "field_locale__hint": "Увядзіце лакалізацыю",
    "field_locale_to": "Лакалізацыя (да)",
    "field_locale_to__hint": "Увядзіце лакалізацыю (да)",
    "item_new": "[Новы элемент]",
    "game_phonetics": "Фанетыка",
    "game_harmonica": "Гармонік",
    "game_articulation": "Артыкуляцыя",
    "error_not_found": "Памылка: Запісаны файл не знойдзен",
    "edit_structure": "Рэдагаваць структуру",
    "button_update": "Абнавіць",
    "button_stop_recording": "Спыніць запіс",
    "button_shuffle": "Перамяшаць",
    "button_select": "Выбраць",
    "button_save": "Захаваць",
    "button_record": "Запісаць",
    "button_processing": "Апрацоўка",
    "button_play": "Прайграць",
    "button_listen": "Праслухаць",
    "button_expand": "Раскрыць",
    "button_edit": "Рэдагаваць",
    "button_collapse": "Згарнуць",
    "button_clear": "Ачысціць",
    "button_choose": "Выбраць",
    "button_back": "Вярнуцца",
    "button_add": "Дадаць",
    "_": "Фатальная памылка"
}
