labels_be = {
    "lang_pair_io_title": "Імпарт / Экспарт моўнай пары",
    "lang_pair_export_btn": "Экспарт",
    "lang_pair_import_btn": "Імпарт",
    "lang_pair_file_path": "Файл",
    "lang_pair_merge_import": "Зліць (дадаць словы, захаваць існуючыя)",
    "vocab_translation_label": "Пераклад (Мэтавая мова) *",
    "vocab_sound_label": "Шлях да аўдыё файла (Неабавязкова)",
    "vocab_origin_label": "Арыгінал (Зыходная мова) *",
    "vocab_image_label": "Шлях да выявы (Неабавязкова)",
    "vocab_difficulty_label": "Узровень складанасці (0-10)",
    "vocab_category_label": "Катэгорыя (Аўта-запаўненне)",
    "vocab_add_title": "Дадаць новае слова",
    "status_select_sentence": "Выберыце сказ",
    "status_saving": "Захоўваецца...",
    "status_recording_stopped": "Запіс спынены",
    "status_recording": "Запіс...",
    "status_comparing_audio": "Параўнанне вымаўлення...",
    "status_comparison_result": "Ацэнка вымаўлення",
    "status_comparison_preparing": "Падрыхтоўка параўнання...",
    "status_comparison_processing": "Аналіз вымаўлення...",
    "status_comparison_finalizing": "Фарміраванне ацэнкі...",
    "status_comparison_no_segments": "Пакуль няма ацэнак па сегментах",
    "status_comparison_error": "Не ўдалося выканаць параўнанне",
    "status_comparison_unavailable": "Параўнанне недаступнае на гэтай прыладзе",
    "status_comparison_missing_reference": "Выберыце сказ перад праверкай вымаўлення",
    "label_segment_short": "С",
    "label_word_short": "Сл",
    "status_loading": "Загрузка...",
    "language_pair_to_label": "Мэтавая мова *",
    "language_pair_name_label": "Назва пары *",
    "language_pair_logo_label": "Шлях да лагатыпу (Неабавязкова)",
    "language_pair_from_label": "Зыходная мова *",
    "language_pair_add_title": "Дадаць моўную пару",
    "language_pair_select_language": "Выберыце мову",
    "item_new": "[Новы элемент]",
    "game_speaking": "Гаварэнне",
    "game_phonetics": "Фанетыка",
    "game_harmonica_acoustic": "Акустычны гармонік",
    "game_harmonica": "Гармонік",
    "game_cards": "Карткі",
    "game_articulation": "Артыкуляцыя",
    "field_text__hint": "Увядзіце тэкст",
    "field_text": "Загаловак",
    "field_store_path__hint": "Увядзіце шлях да сховішча дадзеных",
    "field_store_path": "Шлях да сховішча дадзеных",
    "field_source__hint": "Увядзіце крыніцу",
    "field_source": "Крыніца",
    "field_route_path__hint": "Увядзіце шлях маршруту",
    "field_route_path": "Шлях маршруту",
    "field_logo__hint": "Увядзіце лагатып",
    "field_logo": "Лагатып",
    "field_locale_to__hint": "Увядзіце лакалізацыю (да)",
    "field_locale_to": "Лакалізацыя (да)",
    "field_locale__hint": "Увядзіце лакалізацыю",
    "field_locale": "Лакалізацыя",
    "error_not_found": "Памылка: Запісаны файл не знойдзен",
    "edit_structure": "Рэдагаваць структуру",
    "category_vocab_label": "Крыніца слоўніка *",
    "category_order_label": "Парадак адлюстравання (Неабавязкова)",
    "category_name_label": "Назва катэгорыі *",
    "category_icon_label": "Шлях да іконкі (Неабавязкова)",
    "category_add_title": "Дадаць новую катэгорыю",
    "button_update": "Абнавіць",
    "button_stop_recording": "Спыніць запіс",
    "button_shuffle": "Перамяшаць",
    "button_settings": "Налады",
    "button_select": "Выбраць",
    "button_save": "Захаваць",
    "button_record": "Запісаць",
    "button_processing": "Апрацоўка",
    "button_play": "Прайграць",
    "button_listen": "Праслухаць",
    "button_flip": "Павярнуць",
    "button_expand": "Раскрыць",
    "button_edit": "Рэдагаваць",
    "button_collapse": "Згарнуць",
    "button_clear": "Ачысціць",
    "button_choose": "Выбраць",
    "button_cancel": "Адмена",
    "button_delete": "Выдаліць",
    "button_back": "Вярнуцца",
    "button_add": "Дадаць",
    "button_add_word": "Дадаць слова",
    "theme_dark_mode": "Цёмная тэма",
    "theme_light_mode": "Светлая тэма",
    "search": "Пошук...",
    "dictionaries_manage_title": "Кіраванне слоўнікам",
    "_": "Фатальная памылка"
}
