labels_en = {
    "status_saving": "Saving...",
    "status_select_sentence": "Select a sentence",
    "status_recording": "Recording...",
    "status_recording_stopped": "Recording stopped",
    "field_text": "Title",
    "field_text__hint": "Enter title",
    "field_source": "Source",
    "field_source__hint": "Enter source",
    "field_logo": "Logo",
    "field_logo__hint": "Enter logo",
    "field_store_path": "Store Path",
    "field_store_path__hint": "Enter store path",
    "field_route_path": "Route Path",
    "field_route_path__hint": "Enter route path",
    "field_locale": "Locale",
    "field_locale__hint": "Enter locale",
    "field_locale_to": "Locale (to)",
    "field_locale_to__hint": "Enter locale (to)",
    "item_new": "[New Item]",
    "game_phonetics": "Phonetics",
    "game_harmonica": "Harmonica",
    "game_articulation": "Articulation",
    "error_not_found": "Error: No recorded file found",
    "edit_structure": "Edit Structure",
    "button_update": "Update",
    "button_stop_recording": "Stop Recording",
    "button_shuffle": "Shuffle",
    "button_select": "Select",
    "button_save": "Save",
    "button_record": "Record",
    "button_processing": "Processing",
    "button_play": "Play",
    "button_listen": "Listen",
    "button_expand": "Expand",
    "button_edit": "Edit",
    "button_clear": "Clear",
    "button_choose": "Choose",
    "button_add": "Add",
    "_": "Fatal Error"
}
