labels = {
    "BE": {
        "status_saving": "Захоўваецца...",
        "status_select_sentence": "Выберыце сказ",
        "status_recording": "Запіс...",
        "status_recording_stopped": "Запіс спынены",
        "game_phonetics": "Фанетыка",
        "game_harmonica": "Гармонік",
        "game_articulation": "Артыкуляцыя",
        "error_not_found": "Памылка: Запісаны файл не знойдзен",
        "button_update": "Абнавіць",
        "button_stop_recording": "Спыніць запіс",
        "button_shuffle": "Перамяшаць",
        "button_select": "Выбраць",
        "button_save": "Захаваць",
        "button_record": "Запісаць",
        "button_processing": "Апрацоўка",
        "button_play": "Прайграць",
        "button_listen": "Праслухаць",
        "button_expand": "Раскрыць",
        "button_edit": "Рэдагаваць",
        "button_clear": "Ачысціць",
        "button_choose": "Выбраць",
        "button_add": "Дадаць",
        "_": "Фатальная памылка"
    },
    "EN": {
        "status_saving": "Saving...",
        "status_select_sentence": "Select a sentence",
        "status_recording": "Recording...",
        "status_recording_stopped": "Recording stopped",
        "game_phonetics": "Phonetics",
        "game_harmonica": "Harmonica",
        "game_articulation": "Articulation",
        "error_not_found": "Error: No recorded file found",
        "button_update": "Update",
        "button_stop_recording": "Stop Recording",
        "button_shuffle": "Shuffle",
        "button_select": "Select",
        "button_save": "Save",
        "button_record": "Record",
        "button_processing": "Processing",
        "button_play": "Play",
        "button_listen": "Listen",
        "button_expand": "Expand",
        "button_edit": "Edit",
        "button_clear": "Clear",
        "button_choose": "Choose",
        "button_add": "Add",
        "_": "Fatal Error"
    },
    "RU": {
        "status_saving": "Сохранение...",
        "status_select_sentence": "Выберите предложение",
        "status_recording": "Запись...",
        "status_recording_stopped": "Запись остановлена",
        "game_phonetics": "Фонетика",
        "game_harmonica": "Гармошка",
        "game_articulation": "Артикуляция",
        "error_not_found": "Ошибка: Записанный файл не найден",
        "button_update": "Обновить",
        "button_stop_recording": "Остановить запись",
        "button_shuffle": "Перемешать",
        "button_select": "Выбрать",
        "button_save": "Сохранить",
        "button_record": "Записать",
        "button_processing": "Обработка...",
        "button_play": "Играть",
        "button_listen": "Слушать",
        "button_expand": "Раскрыть",
        "button_edit": "Редактировать",
        "button_clear": "Очистить",
        "button_choose": "Выбрать",
        "button_add": "Добавить",
        "_": "Фатальная ошибка"
    },
    "UK": {
        "status_saving": "Збереження...",
        "status_select_sentence": "Виберіть речення",
        "status_recording": "Запис...",
        "status_recording_stopped": "Запис зупинено",
        "game_phonetics": "Фонетика",
        "game_harmonica": "Гармоніка",
        "game_articulation": "Артикуляція",
        "error_not_found": "Помилка: Записаний файл не знайдено",
        "button_update": "Оновити",
        "button_stop_recording": "Зупинити запис",
        "button_shuffle": "Перемішати",
        "button_select": "Вибрати",
        "button_save": "Зберегти",
        "button_record": "Записати",
        "button_processing": "Обробка",
        "button_play": "Відтворити",
        "button_listen": "Слухати",
        "button_expand": "Розкрити",
        "button_edit": "Редагувати",
        "button_clear": "Очистити",
        "button_choose": "Вибрати",
        "button_add": "Додати",
        "_": "Фатальна помилка"        
    }
}
