labels_fr = {
    "vocab_translation_label": "Traduction (Langue cible) *",
    "vocab_sound_label": "Chemin du fichier audio (Optionnel)",
    "vocab_origin_label": "Origine (Langue source) *",
    "vocab_image_label": "Chemin du fichier image (Optionnel)",
    "vocab_difficulty_label": "Niveau de difficulté (0-10)",
    "vocab_category_label": "Catégorie (Rempli automatiquement)",
    "vocab_add_title": "Ajouter un nouvel élément de vocabulaire",
    "theme_light_mode": "Mode clair",
    "theme_dark_mode": "Mode sombre",
    "status_select_sentence": "Sélectionnez une phrase",
    "status_saving": "Enregistrement...",
    "status_recording_stopped": "Enregistrement arrêté",
    "status_recording": "Enregistrement...",
    "status_loading": "Chargement...",
    "status_comparison_unavailable": "Comparaison indisponible sur cet appareil",
    "status_comparison_result": "Score de prononciation",
    "status_comparison_processing": "Analyse de la prononciation...",
    "status_comparison_preparing": "Préparation de la comparaison...",
    "status_comparison_no_segments": "Aucun score de segment pour le moment",
    "status_comparison_missing_reference": "Choisissez une phrase avant de vérifier la prononciation",
    "status_comparison_finalizing": "Finalisation du score...",
    "status_comparison_error": "La comparaison a échoué",
    "status_comparing_audio": "Comparaison de la prononciation...",
    "search": "Recherche...",
    "language_pair_to_label": "Langue cible *",
    "language_pair_select_language": "Sélectionner une langue",
    "language_pair_name_label": "Nom de la paire *",
    "language_pair_logo_label": "Chemin du logo (Optionnel)",
    "language_pair_from_label": "Langue source *",
    "language_pair_add_title": "Ajouter une paire de langues",
    "lang_pair_merge_import": "Fusionner (ajouter des mots, conserver les existants)",
    "lang_pair_io_title": "Import / Export de la paire de langues",
    "lang_pair_import_title": "Importer la paire de langues",
    "lang_pair_import_btn": "Importer",
    "lang_pair_file_path": "Fichier",
    "lang_pair_export_title": "Exporter la paire de langues",
    "lang_pair_export_btn": "Exporter",
    "lang_pair_browse_btn": "Parcourir…",
    "label_word_short": "M",
    "label_segment_short": "S",
    "item_new": "[Nouvel élément]",
    "game_speaking": "Parler",
    "game_phonetics": "Phonétique",
    "game_harmonica_acoustic": "Harmonica acoustique",
    "game_harmonica": "Harmonica",
    "game_cards": "Cartes",
    "game_articulation": "Articulation",
    "field_text__hint": "Saisissez le titre",
    "field_text": "Titre",
    "field_store_path__hint": "Saisissez le chemin du stockage",
    "field_store_path": "Chemin du stockage",
    "field_source__hint": "Saisissez la source",
    "field_source": "Source",
    "field_route_path__hint": "Saisissez le chemin de la route",
    "field_route_path": "Chemin de la route",
    "field_logo__hint": "Saisissez le logo",
    "field_logo": "Logo",
    "field_locale_to__hint": "Saisissez la langue cible",
    "field_locale_to": "Langue (cible)",
    "field_locale__hint": "Saisissez la langue",
    "field_locale": "Langue",
    "error_not_found": "Erreur : aucun fichier enregistré trouvé",
    "edit_structure": "Modifier la structure",
    "dictionaries_manage_title": "Gérer le dictionnaire",
    "category_vocab_label": "Source du vocabulaire *",
    "category_order_label": "Ordre d'affichage (Optionnel)",
    "category_name_label": "Nom de la catégorie *",
    "category_icon_label": "Chemin de l'icône (Optionnel)",
    "category_add_title": "Ajouter une nouvelle catégorie",
    "button_update": "Mettre à jour",
    "button_stop_recording": "Arrêter l'enregistrement",
    "button_shuffle": "Mélanger",
    "button_settings": "Paramètres",
    "button_select": "Sélectionner",
    "button_save": "Enregistrer",
    "button_record": "Enregistrer",
    "button_processing": "Traitement",
    "button_play": "Lecture",
    "button_listen": "Écouter",
    "button_flip": "Retourner",
    "button_expand": "Développer",
    "button_edit": "Modifier",
    "button_delete": "Supprimer",
    "button_collapse": "Réduire",
    "button_clear": "Effacer",
    "button_choose": "Choisir",
    "button_cancel": "Annuler",
    "button_back": "Retour",
    "button_add_word": "Ajouter un mot",
    "button_add": "Ajouter",
    "_": "Erreur fatale"
}
