labels_en = {
    "vocab_translation_label": "Translation (Target Language) *",
    "vocab_sound_label": "Sound File Path (Optional)",
    "vocab_origin_label": "Origin (Source Language) *",
    "vocab_image_label": "Image File Path (Optional)",
    "vocab_difficulty_label": "Difficulty Level (0-10)",
    "vocab_category_label": "Category (Auto-filled)",
    "vocab_add_title": "Add New Vocabulary Item",
    "status_select_sentence": "Select a sentence",
    "status_saving": "Saving...",
    "status_recording_stopped": "Recording stopped",
    "status_recording": "Recording...",
    "status_loading": "Loading...",
    "item_new": "[New Item]",
    "game_speaking": "Speaking",
    "game_phonetics": "Phonetics",
    "game_harmonica_acoustic": "Acoustic Harmonica",
    "game_harmonica": "Harmonica",
    "game_cards": "Cards",
    "game_articulation": "Articulation",
    "field_text__hint": "Enter title",
    "status_saving": "Saving...",
    "status_recording_stopped": "Recording stopped",
    "status_recording": "Recording...",
    "status_loading": "Loading...",
    "item_new": "[New Item]",
    "game_speaking": "Speaking",
    "game_phonetics": "Phonetics",
    "game_harmonica_acoustic": "Acoustic Harmonica",
    "game_harmonica": "Harmonica",
    "game_cards": "Cards",
    "game_articulation": "Articulation",
    "field_text__hint": "Enter title",
    "field_text": "Title",
    "field_store_path__hint": "Enter store path",
    "field_store_path": "Store Path",
    "field_source__hint": "Enter source",
    "field_source": "Source",
    "field_route_path__hint": "Enter route path",
    "field_route_path": "Route Path",
    "field_logo__hint": "Enter logo",
    "field_logo": "Logo",
    "field_locale_to__hint": "Enter locale (to)",
    "field_locale_to": "Locale (to)",
    "field_locale__hint": "Enter locale",
    "field_locale": "Locale",
    "error_not_found": "Error: No recorded file found",
    "edit_structure": "Edit Structure",
    "category_vocab_label": "Vocabulary Source *",
    "category_order_label": "Display Order (Optional)",
    "category_name_label": "Category Name *",
    "category_icon_label": "Icon Path (Optional)",
    "category_add_title": "Add New Category",
    "language_pair_add_title": "Add Language Pair",
    "language_pair_from_label": "Source Language *",
    "language_pair_to_label": "Target Language *",
    "language_pair_name_label": "Pair Name *",
    "language_pair_logo_label": "Logo Path (Optional)",
    "button_update": "Update",
    "field_store_path__hint": "Enter store path",
    "field_store_path": "Store Path",
    "field_source__hint": "Enter source",
    "field_source": "Source",
    "field_route_path__hint": "Enter route path",
    "field_route_path": "Route Path",
    "field_logo__hint": "Enter logo",
    "field_logo": "Logo",
    "field_locale_to__hint": "Enter locale (to)",
    "field_locale_to": "Locale (to)",
    "field_locale__hint": "Enter locale",
    "field_locale": "Locale",
    "error_not_found": "Error: No recorded file found",
    "edit_structure": "Edit Structure",
    "button_update": "Update",
    "button_stop_recording": "Stop Recording",
    "button_shuffle": "Shuffle",
    "button_settings": "Settings",
    "button_select": "Select",
    "button_save": "Save",
    "button_record": "Record",
    "button_processing": "Processing",
    "button_play": "Play",
    "button_listen": "Listen",
    "button_flip": "Flip",
    "button_expand": "Expand",
    "button_edit": "Edit",
    "button_collapse": "Collapse",
    "button_clear": "Clear",
    "button_choose": "Choose",
    "button_cancel": "Cancel",
    "button_back": "Back",
    "button_add": "Add",
    "_": "Fatal Error"
}
