labels_uk = {
    "status_select_sentence": "Виберіть речення",
    "status_saving": "Збереження...",
    "status_recording_stopped": "Запис зупинено",
    "status_recording": "Запис...",
    "status_loading": "Загрузка...",
    "item_new": "[Новий елемент]",
    "game_phonetics": "Фонетика",
    "game_harmonica": "Гармоніка",
    "game_cards": "Картки",
    "game_articulation": "Артикуляція",
    "field_text__hint": "Введіть текст",
    "field_text": "Заголовок",
    "field_store_path__hint": "Введіть шлях до сховища даних",
    "field_store_path": "Шлях до сховища даних",
    "field_source__hint": "Введіть джерело",
    "field_source": "Джерело",
    "field_route_path__hint": "Введіть шлях маршруту",
    "field_route_path": "Шлях маршруту",
    "field_logo__hint": "Введіть логотип",
    "field_logo": "Логотип",
    "field_locale_to__hint": "Введіть локалізацію (до)",
    "field_locale_to": "Локалізація (до)",
    "field_locale__hint": "Введіть локалізацію",
    "field_locale": "Локалізація",
    "error_not_found": "Помилка: Записаний файл не знайдено",
    "edit_structure": "Редагувати структуру",
    "button_update": "Оновити",
    "button_stop_recording": "Зупинити запис",
    "button_shuffle": "Перемішати",
    "button_select": "Вибрати",
    "button_save": "Зберегти",
    "button_record": "Записати",
    "button_processing": "Обробка",
    "button_play": "Відтворити",
    "button_listen": "Слухати",
    "button_flip": "Перевернути",
    "button_expand": "Розкрити",
    "button_edit": "Редагувати",
    "button_collapse": "Згорнути",
    "button_clear": "Очистити",
    "button_choose": "Вибрати",
    "button_back": "Назад",
    "button_add": "Додати",
    "_": "Фатальна помилка"
}
