labels = {
    "BE": {
        "status_saving": "Захоўваецца...",
        "status_select_sentence": "Выберыце сказ",
        "status_recording": "Запіс...",
        "status_recording_stopped": "Запіс спынены",
        "field_text": "Загаловак",
        "field_text__hint": "Увядзіце тэкст",
        "field_source": "Крыніца",
        "field_source__hint": "Увядзіце крыніцу",
        "field_logo": "Лагатып",
        "field_logo__hint": "Увядзіце лагатып",
        "field_store_path": "Шлях да сховішча дадзеных",
        "field_store_path__hint": "Увядзіце шлях да сховішча дадзеных",
        "field_route_path": "Шлях маршруту",
        "field_route_path__hint": "Увядзіце шлях маршруту",
        "field_locale": "Лакалізацыя",
        "field_locale__hint": "Увядзіце лакалізацыю",
        "field_locale_to": "Лакалізацыя (да)",
        "field_locale_to__hint": "Увядзіце лакалізацыю (да)",
        "item_new": "[Новы элемент]",
        "game_phonetics": "Фанетыка",
        "game_harmonica": "Гармонік",
        "game_articulation": "Артыкуляцыя",
        "error_not_found": "Памылка: Запісаны файл не знойдзен",
        "edit_structure": "Рэдагаваць структуру",
        "button_update": "Абнавіць",
        "button_stop_recording": "Спыніць запіс",
        "button_shuffle": "Перамяшаць",
        "button_select": "Выбраць",
        "button_save": "Захаваць",
        "button_record": "Запісаць",
        "button_processing": "Апрацоўка",
        "button_play": "Прайграць",
        "button_listen": "Праслухаць",
        "button_expand": "Раскрыць",
        "button_edit": "Рэдагаваць",
        "button_clear": "Ачысціць",
        "button_choose": "Выбраць",
        "button_add": "Дадаць",
        "_": "Фатальная памылка"
    },
    "EN": {
        "status_saving": "Saving...",
        "status_select_sentence": "Select a sentence",
        "status_recording": "Recording...",
        "status_recording_stopped": "Recording stopped",
        "field_text": "Title",
        "field_text__hint": "Enter title",
        "field_source": "Source",
        "field_source__hint": "Enter source",
        "field_logo": "Logo",
        "field_logo__hint": "Enter logo",
        "field_store_path": "Store Path",
        "field_store_path__hint": "Enter store path",
        "field_route_path": "Route Path",
        "field_route_path__hint": "Enter route path",
        "field_locale": "Locale",
        "field_locale__hint": "Enter locale",
        "field_locale_to": "Locale (to)",
        "field_locale_to__hint": "Enter locale (to)",
        "item_new": "[New Item]",
        "game_phonetics": "Phonetics",
        "game_harmonica": "Harmonica",
        "game_articulation": "Articulation",
        "error_not_found": "Error: No recorded file found",
        "edit_structure": "Edit Structure",
        "button_update": "Update",
        "button_stop_recording": "Stop Recording",
        "button_shuffle": "Shuffle",
        "button_select": "Select",
        "button_save": "Save",
        "button_record": "Record",
        "button_processing": "Processing",
        "button_play": "Play",
        "button_listen": "Listen",
        "button_expand": "Expand",
        "button_edit": "Edit",
        "button_clear": "Clear",
        "button_choose": "Choose",
        "button_add": "Add",
        "_": "Fatal Error"
    },
    "RU": {
        "status_saving": "Сохранение...",
        "status_select_sentence": "Выберите предложение",
        "status_recording": "Запись...",
        "status_recording_stopped": "Запись остановлена",
        "field_text": "Заголовок",
        "field_text__hint": "Введите текст",
        "field_source": "Источник",
        "field_source__hint": "Введите источник",
        "field_logo": "Логотип",
        "field_logo__hint": "Введите логотип",
        "field_store_path": "Путь к хранилищу данных",
        "field_store_path__hint": "Введите путь к хранилищу данных",
        "field_route_path": "Путь маршрута",
        "field_route_path__hint": "Введите путь маршрута",
        "field_locale": "Локализация",
        "field_locale__hint": "Введите локализацию",
        "field_locale_to": "Локализация (до)",
        "field_locale_to__hint": "Введите локализацию (до)",
        "item_new": "[Новый элемент]",
        "game_phonetics": "Фонетика",
        "game_harmonica": "Гармошка",
        "game_articulation": "Артикуляция",
        "error_not_found": "Ошибка: Записанный файл не найден",
        "edit_structure": "Редактировать структуру",
        "button_update": "Обновить",
        "button_stop_recording": "Остановить запись",
        "button_shuffle": "Перемешать",
        "button_select": "Выбрать",
        "button_save": "Сохранить",
        "button_record": "Записать",
        "button_processing": "Обработка...",
        "button_play": "Играть",
        "button_listen": "Слушать",
        "button_expand": "Раскрыть",
        "button_edit": "Редактировать",
        "button_clear": "Очистить",
        "button_choose": "Выбрать",
        "button_add": "Добавить",
        "_": "Фатальная ошибка"
    },
    "UK": {
        "status_saving": "Збереження...",
        "status_select_sentence": "Виберіть речення",
        "status_recording": "Запис...",
        "status_recording_stopped": "Запис зупинено",
        "field_text": "Заголовок",
        "field_text__hint": "Введіть текст",
        "field_source": "Джерело",
        "field_source__hint": "Введіть джерело",
        "field_logo": "Логотип",
        "field_logo__hint": "Введіть логотип",
        "field_store_path": "Шлях до сховища даних",
        "field_store_path__hint": "Введіть шлях до сховища даних",
        "field_route_path": "Шлях маршруту",
        "field_route_path__hint": "Введіть шлях маршруту",
        "field_locale": "Локалізація",
        "field_locale__hint": "Введіть локалізацію",
        "field_locale_to": "Локалізація (до)",
        "field_locale_to__hint": "Введіть локалізацію (до)",
        "item_new": "[Новий елемент]",
        "game_phonetics": "Фонетика",
        "game_harmonica": "Гармоніка",
        "game_articulation": "Артикуляція",
        "error_not_found": "Помилка: Записаний файл не знайдено",
        "edit_structure": "Редагувати структуру",
        "button_update": "Оновити",
        "button_stop_recording": "Зупинити запис",
        "button_shuffle": "Перемішати",
        "button_select": "Вибрати",
        "button_save": "Зберегти",
        "button_record": "Записати",
        "button_processing": "Обробка",
        "button_play": "Відтворити",
        "button_listen": "Слухати",
        "button_expand": "Розкрити",
        "button_edit": "Редагувати",
        "button_clear": "Очистити",
        "button_choose": "Вибрати",
        "button_add": "Додати",
        "_": "Фатальна помилка"        
    }
}
