labels_pl = {
    "vocab_translation_label": "Tłumaczenie (Język docelowy) *",
    "vocab_sound_label": "Ścieżka pliku dźwięku (Opcjonalnie)",
    "vocab_origin_label": "Źródło (Język źródłowy) *",
    "vocab_image_label": "Ścieżka pliku obrazu (Opcjonalnie)",
    "vocab_difficulty_label": "Poziom trudności (0-10)",
    "vocab_category_label": "Kategoria (Auto-wypełniana)",
    "vocab_add_title": "Dodaj nowy element słownika",
    "status_select_sentence": "Wybierz zdanie",
    "status_saving": "Zapisywanie...",
    "status_recording_stopped": "Nagrywanie zatrzymane",
    "status_recording": "Nagrywanie...",
    "status_comparing_audio": "Porównywanie wymowy...",
    "status_comparison_result": "Wynik wymowy",
    "status_comparison_preparing": "Przygotowywanie porównania...",
    "status_comparison_processing": "Analiza wymowy...",
    "status_comparison_finalizing": "Finalizowanie wyniku...",
    "status_comparison_no_segments": "Brak wyników segmentów",
    "status_comparison_error": "Porównanie nie powiodło się",
    "status_comparison_unavailable": "Porównanie niedostępne na tym urządzeniu",
    "status_comparison_missing_reference": "Wybierz zdanie przed sprawdzeniem wymowy",
    "label_segment_short": "S",
    "label_word_short": "W",
    "status_loading": "Ładowanie...",
    "language_pair_to_label": "Język docelowy *",
    "language_pair_name_label": "Nazwa pary *",
    "language_pair_logo_label": "Ścieżka logo (Opcjonalnie)",
    "language_pair_from_label": "Język źródłowy *",
    "language_pair_add_title": "Dodaj parę języków",
    "language_pair_select_language": "Wybierz język",
    "item_new": "[Nowy element]",
    "game_speaking": "Mówienie",
    "game_phonetics": "Fonetyka",
    "game_harmonica_acoustic": "Harmonika akustyczna",
    "game_harmonica": "Harmonika",
    "game_cards": "Karty",
    "game_articulation": "Artykulacja",
    "field_text__hint": "Wpisz tytuł",
    "field_text": "Tytuł",
    "field_store_path__hint": "Wpisz ścieżkę magazynu",
    "field_store_path": "Ścieżka magazynu",
    "field_source__hint": "Wpisz źródło",
    "field_source": "Źródło",
    "field_route_path__hint": "Wpisz ścieżkę trasy",
    "field_route_path": "Ścieżka trasy",
    "field_logo__hint": "Wpisz logo",
    "field_logo": "Logo",
    "field_locale_to__hint": "Wpisz ustawienie regionalne (do)",
    "field_locale_to": "Ustawienie regionalne (do)",
    "field_locale__hint": "Wpisz ustawienie regionalne",
    "field_locale": "Ustawienie regionalne",
    "error_not_found": "Błąd: nie znaleziono nagranego pliku",
    "edit_structure": "Edytuj strukturę",
    "category_vocab_label": "Źródło słownika *",
    "category_order_label": "Porządek wyświetlania (Opcjonalnie)",
    "category_name_label": "Nazwa kategorii *",
    "category_icon_label": "Ścieżka ikony (Opcjonalnie)",
    "category_add_title": "Dodaj nową kategorię",
    "button_update": "Aktualizuj",
    "button_stop_recording": "Zatrzymaj nagrywanie",
    "button_shuffle": "Mieszaj",
    "button_settings": "Ustawienia",
    "button_select": "Wybierz",
    "button_save": "Zapisz",
    "button_record": "Nagraj",
    "button_processing": "Przetwarzanie",
    "button_play": "Odtwórz",
    "button_listen": "Posłuchaj",
    "button_flip": "Odwróć",
    "button_expand": "Rozwiń",
    "button_edit": "Edytuj",
    "button_collapse": "Zwiń",
    "button_clear": "Wyczyść",
    "button_choose": "Wybierz",
    "button_cancel": "Anuluj",
    "button_delete": "Usuń",
    "button_back": "Wstecz",
    "button_add": "Dodaj",
    "button_add_word": "Dodaj słowo",
    "search": "Szukaj...",
    "dictionaries_manage_title": "Zarządzaj słownikiem",
    "_": "Błąd krytyczny"
}
