labels_de = {
    "vocab_translation_label": "Übersetzung (Zielsprache) *",
    "vocab_sound_label": "Audiodateipfad (Optional)",
    "vocab_origin_label": "Ursprung (Ausgangssprache) *",
    "vocab_image_label": "Bilddateipfad (Optional)",
    "vocab_difficulty_label": "Schwierigkeitsgrad (0-10)",
    "vocab_category_label": "Kategorie (Automatisch ausgefüllt)",
    "vocab_add_title": "Neues Vokabular hinzufügen",
    "theme_light_mode": "Hellmodus",
    "theme_dark_mode": "Dunkelmodus",
    "status_select_sentence": "Wählen Sie einen Satz",
    "status_saving": "Wird gespeichert...",
    "status_recording_stopped": "Aufnahme gestoppt",
    "status_recording": "Aufnahme...",
    "status_loading": "Wird geladen...",
    "status_comparison_unavailable": "Vergleich auf diesem Gerät nicht verfügbar",
    "status_comparison_result": "Aussprachebewertung",
    "status_comparison_processing": "Aussprache wird analysiert...",
    "status_comparison_preparing": "Vergleich wird vorbereitet...",
    "status_comparison_no_segments": "Noch keine Segmentbewertungen",
    "status_comparison_missing_reference": "Wählen Sie vor dem Prüfen der Aussprache einen Satz",
    "status_comparison_finalizing": "Bewertung wird abgeschlossen...",
    "status_comparison_error": "Vergleich fehlgeschlagen",
    "status_comparing_audio": "Aussprache wird verglichen...",
    "search": "Suche...",
    "language_pair_to_label": "Zielsprache *",
    "language_pair_select_language": "Sprache auswählen",
    "language_pair_name_label": "Paarname *",
    "language_pair_logo_label": "Logopfad (Optional)",
    "language_pair_from_label": "Ausgangssprache *",
    "language_pair_add_title": "Sprachpaar hinzufügen",
    "lang_pair_merge_import": "Zusammenführen (Wörter anhängen, vorhandene behalten)",
    "lang_pair_io_title": "Import / Export des Sprachpaars",
    "lang_pair_import_title": "Sprachpaar importieren",
    "lang_pair_import_btn": "Importieren",
    "lang_pair_file_path": "Datei",
    "lang_pair_export_title": "Sprachpaar exportieren",
    "lang_pair_export_btn": "Exportieren",
    "lang_pair_browse_btn": "Durchsuchen…",
    "label_word_short": "W",
    "label_segment_short": "S",
    "item_new": "[Neues Element]",
    "game_speaking": "Sprechen",
    "game_phonetics": "Phonetik",
    "game_harmonica_acoustic": "Akustische Harmonika",
    "game_harmonica": "Harmonika",
    "game_cards": "Karten",
    "game_articulation": "Artikulation",
    "field_text__hint": "Titel eingeben",
    "field_text": "Titel",
    "field_store_path__hint": "Speicherpfad eingeben",
    "field_store_path": "Speicherpfad",
    "field_source__hint": "Quelle eingeben",
    "field_source": "Quelle",
    "field_route_path__hint": "Routenpfad eingeben",
    "field_route_path": "Routenpfad",
    "field_logo__hint": "Logo eingeben",
    "field_logo": "Logo",
    "field_locale_to__hint": "Locale eingeben (Ziel)",
    "field_locale_to": "Locale (Ziel)",
    "field_locale__hint": "Locale eingeben",
    "field_locale": "Locale",
    "error_not_found": "Fehler: Keine aufgezeichnete Datei gefunden",
    "edit_structure": "Struktur bearbeiten",
    "dictionaries_manage_title": "Wörterbuch verwalten",
    "category_vocab_label": "Wörterbuchquelle *",
    "category_order_label": "Anzeigereihenfolge (Optional)",
    "category_name_label": "Kategoriename *",
    "category_icon_label": "Symbolpfad (Optional)",
    "category_add_title": "Neue Kategorie hinzufügen",
    "button_update": "Aktualisieren",
    "button_stop_recording": "Aufnahme stoppen",
    "button_shuffle": "Mischen",
    "button_settings": "Einstellungen",
    "button_select": "Auswählen",
    "button_save": "Speichern",
    "button_record": "Aufnehmen",
    "button_processing": "Verarbeitung",
    "button_play": "Abspielen",
    "button_listen": "Anhören",
    "button_flip": "Drehen",
    "button_expand": "Erweitern",
    "button_edit": "Bearbeiten",
    "button_delete": "Löschen",
    "button_collapse": "Zusammenklappen",
    "button_clear": "Leeren",
    "button_choose": "Auswählen",
    "button_cancel": "Abbrechen",
    "button_back": "Zurück",
    "button_add_word": "Wort hinzufügen",
    "button_add": "Hinzufügen",
    "_": "Fataler Fehler"
}
