labels_ru = {
    "status_select_sentence": "Выберите предложение",
    "status_saving": "Сохранение...",
    "status_recording_stopped": "Запись остановлена",
    "status_recording": "Запись...",
    "status_loading": "Загрузка...",
    "item_new": "[Новый элемент]",
    "game_phonetics": "Фонетика",
    "game_harmonica": "Гармошка",
    "game_cards": "Карты",
    "game_articulation": "Артикуляция",
    "field_text__hint": "Введите текст",
    "field_text": "Заголовок",
    "field_store_path__hint": "Введите путь к хранилищу данных",
    "field_store_path": "Путь к хранилищу данных",
    "field_source__hint": "Введите источник",
    "field_source": "Источник",
    "field_route_path__hint": "Введите путь маршрута",
    "field_route_path": "Путь маршрута",
    "field_logo__hint": "Введите логотип",
    "field_logo": "Логотип",
    "field_locale_to__hint": "Введите локализацию (до)",
    "field_locale_to": "Локализация (до)",
    "field_locale__hint": "Введите локализацию",
    "field_locale": "Локализация",
    "error_not_found": "Ошибка: Записанный файл не найден",
    "edit_structure": "Редактировать структуру",
    "button_update": "Обновить",
    "button_stop_recording": "Остановить запись",
    "button_shuffle": "Перемешать",
    "button_select": "Выбрать",
    "button_save": "Сохранить",
    "button_record": "Записать",
    "button_processing": "Обработка...",
    "button_play": "Играть",
    "button_listen": "Слушать",
    "button_flip": "Перевернуть",
    "button_expand": "Раскрыть",
    "button_edit": "Редактировать",
    "button_collapse": "Свернуть",
    "button_clear": "Очистить",
    "button_choose": "Выбрать",
    "button_back": "Вернуться",
    "button_add": "Добавить",
    "_": "Фатальная ошибка"
}
