# Copyright 2026 The terCAD team. All rights reserved.
# Use of this source code is governed by a CC BY-NC-ND 4.0 license that can be found in the LICENSE file.

"""Canonical worldwide language catalog.

The keys are uppercase ISO-style language indicators and the values are the
language names written in their original/native form.
"""

WORLD_LANGUAGES = {
    "AF": "Afrikaans",
    "AM": "አማርኛ",
    "AR": "العربية",
    "AZ": "Azərbaycan dili",
    "BE": "Беларуская",
    "BG": "Български",
    "BN": "বাংলা",
    "BS": "Bosanski",
    "CA": "Català",
    "CS": "Čeština",
    "CY": "Cymraeg",
    "DA": "Dansk",
    "DE": "Deutsch",
    "EL": "Ελληνικά",
    "EN": "English",
    "ES": "Español",
    "ET": "Eesti",
    "EU": "Euskara",
    "FA": "فارسی",
    "FI": "Suomi",
    "FR": "Français",
    "GA": "Gaeilge",
    "GL": "Galego",
    "GU": "ગુજરાતી",
    "HE": "עברית",
    "HI": "हिन्दी",
    "HR": "Hrvatski",
    "HU": "Magyar",
    "HY": "Հայերեն",
    "ID": "Bahasa Indonesia",
    "IS": "Íslenska",
    "IT": "Italiano",
    "JA": "日本語",
    "KA": "ქართული",
    "KK": "Қазақ тілі",
    "KM": "ខ្មែរ",
    "KN": "ಕನ್ನಡ",
    "KO": "한국어",
    "KY": "Кыргызча",
    "LT": "Lietuvių",
    "LV": "Latviešu",
    "MK": "Македонски",
    "ML": "മലയാളം",
    "MR": "मराठी",
    "MS": "Bahasa Melayu",
    "NB": "Norsk bokmål",
    "NE": "नेपाली",
    "NL": "Nederlands",
    "NO": "Norsk",
    "PA": "ਪੰਜਾਬੀ",
    "PL": "Polski",
    "PT": "Português",
    "RO": "Română",
    "RU": "Русский",
    "SA": "संस्कृतम्",
    "SK": "Slovenčina",
    "SL": "Slovenščina",
    "SQ": "Shqip",
    "SR": "Srpski",
    "SV": "Svenska",
    "SW": "Kiswahili",
    "TA": "தமிழ்",
    "TE": "తెలుగు",
    "TH": "ไทย",
    "TR": "Türkçe",
    "UK": "Українська",
    "UR": "اردو",
    "VI": "Tiếng Việt",
    "ZH": "中文",
}
